{"name": "Проверка неуспешной авторизации с невалидными данными", "status": "passed", "parameters": [{"name": "user_data", "value": "{'password': 'password', 'name': 'Username'}"}], "start": 1732195063477, "stop": 1732195065106, "uuid": "f2d4536e-74c1-4860-97fa-089556643776", "historyId": "353d5d7437e2ac8b894ab0040f3d1215", "testCaseId": "c498ccdde6dd018dcbd10a7ef19133e8", "fullName": "tests.test_edit_user.TestEditUser#test_autorization_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_edit_user"}, {"name": "subSuite", "value": "TestEditUser"}, {"name": "host", "value": "LAPTOP-APHBTB3O"}, {"name": "thread", "value": "14376-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_edit_user"}]}